everything now is according to my needs

diff --git a/src/display-visor b/src/display-visor
--- a/src/display-visor
+++ b/src/display-visor
@@ -1,188 +1,200 @@
 #!/bin/bash
 version="0.4"
 
-usage ()
-{
+usage() {
 	echo \
-'Usage: display-visor [-f] [-i] [-l [switch]]
+  'Usage: display-visor [-f] [-i] [-l [switch]]
 
-	-f, --feh	Run feh bg script.
-                         Executes ~/.fehbg upon completion.
-	-i, --i3	Test for i3wm instance.
-                         For avoiding conflict with multiple environments.
-	-l, --lid	Check laptop lid status.
-                         Ignored/Assumed closed if not given. 
-                         It is possible to specify switch. Defaults to 'LID0'
-                         If unsure, look under /proc/acpi/button/lid/...
-	-v, --version	Print version info.
+    -f, --feh	Run feh bg script.
+                  Executes ~/.fehbg upon completion.
+    -i, --i3	Test for i3wm instance.
+                  For avoiding conflict with multiple environments.
+    -l, --lid	Check laptop lid status.
+                  Ignored/Assumed closed if not given. 
+                  It is possible to specify switch. Defaults to 'LID0'
+                  If unsure, look under /proc/acpi/button/lid/...
+    -v, --version	Print version info.
 
- Useful for setting monitor layouts on system login/resume/hotplug
- when using window managers that do not handle display settings.
+  Useful for setting monitor layouts on system login/resume/hotplug
+  when using window managers that do not handle display settings.
 
- Depends on xorg-xrandr.
+  Depends on xorg-xrandr.
 
-This is free software.
-2015, Michael Heyns <https://github.com/beanaroo>
-'
+  This is free software.
+  2015, Michael Heyns <https://github.com/beanaroo>
+  '
 }
 
-handle_args ()
-{
+handle_args() {
 	while [ "$1" != "" ]; do
 		case $1 in
-			-h | --help )		usage
-								exit
-								;;
-			-f | --feh )		fehbg=true
-								;;
-			-i | --i3 )			i3test=true
-								;;
-			-l | --lid )    	lidtest=true
-                                lidswitch=${2:-LID0}
-                                lidstatus=$(cat /proc/acpi/button/lid/$lidswitch/state 2>/dev/null | awk '{print $NF}')
-                                shift
-								;;
-			-v | --version )	echo "display-visor $version"
-								exit
-								;;
-			* )				usage
-								exit 1
-								;;
+			-h | --help )
+        usage
+        exit;;
+
+			-f | --feh )
+        fehbg=true
+        ;;
+
+			-i | --i3 )
+        i3test=true
+        ;;
+
+			-l | --lid )
+        lidtest=true
+        lidswitch=${2:-LID0}
+        lidstatus=$(cat /proc/acpi/button/lid/$lidswitch/state 2>/dev/null | awk '{print $NF}')
+        shift
+				;;
+
+			-v | --version )
+        echo "display-visor $version"
+				exit
+        ;;
+
+			* )
+        usage
+				exit 1
+        ;;
 		esac
+
 		shift
 	done
 }
 
 
 ## Error Handling
-handle_err ()
-{
-    # Test for running Xorg server
-    if [ -z "$(ps -C Xorg --no-headers)" ]; then
-        echo "$prefix No Xorg server found. Exiting..."
-        exit 1
-    fi
+handle_err() {
+  # Test for running Xorg server
+  if [ -z "$(ps -C Xorg --no-headers)" ]; then
+    echo "$prefix No Xorg server found. Exiting..."
+    exit 1
+  fi
 
-    # Test for running instance of i3
-    if [ "$i3test" == "true" -a -z "$(ps -C i3 --no-headers)" ]; then
-        echo "$prefix i3wm not running. Exiting..."
-        exit 1
-    fi
+  # Test for running instance of i3
+  if [ "$i3test" == "true" -a -z "$(ps -C i3 --no-headers)" ]; then
+    echo "$prefix i3wm not running. Exiting..."
+    exit 1
+  fi
 
-    # Test for valid laptop lid status.
-    if [ "$lidtest" == "true" -a -z "$lidstatus" ]; then
-        echo "$prefix Laptop lid switch $lidswitch not found. Exiting..."
-        exit 1
-    fi
+  # Test for valid laptop lid status.
+  if [ "$lidtest" == "true" -a -z "$lidstatus" ]; then
+    echo "$prefix Laptop lid switch $lidswitch not found. Exiting..."
+    exit 1
+  fi
 }
 
 ## Declare Output Devices
-declare_outputs ()
-{
-    devices=$(find /sys/class/drm/*/status)
-    while read l ; do
-        dir=$(dirname $l)
-        status=$(cat $l)
-        dev=$(echo $dir | cut -d\- -f 2-)
+declare_outputs() {
+  devices=$(find /sys/class/drm/*/status)
 
-        if [ $(expr match  $dev "HDMI") != "0" ]; then
-            dev=HDMI${dev#HDMI-?-}
-        else
-            dev=$(echo $dev | tr -d '-')
-        fi
+  while read l; do
+    dir=$(dirname $l)
+    status=$(cat $l)
+    dev=$(echo $dir | cut -d\- -f 2-)
 
-        if [ "connected" == "$status" ]; then
-            echo "$prefix $dev connected"
-            declare -gA $dev="yes"
-        fi
-    done <<< "$devices"
+    if [ $(expr match  $dev "HDMI") != "0" ]; then
+        dev=HDMI${dev#HDMI-?-}
+    else
+        dev=$(echo $dev | tr -d '-')
+    fi
+
+    if [ "connected" == "$status" ]; then
+        echo "$prefix $dev connected"
+        declare -gA $dev="yes"
+    fi
+
+  done <<< "$devices"
 }
 
 ## Configure monitors for closed lid
-config_closed_lid ()
-{
-    if [ "$lidstatus" == "closed" ]; then
-        echo "$prefix Laptop lid is closed"
-    elif [ -n "$LVDS1" -a -z "$lidtest" ]; then
-        echo "$prefix Laptop display will be ignored unless -l option is set"
-    fi
-    if [ -n "$HDMI1" -a -n "$VGA1" ]; then
-        echo "$prefix SETTING: HDMI1 (Primary) - VGA1 (Right)"
-        xrandr --output LVDS1 --off \
-               --output HDMI1 --auto --primary \
-               --output VGA1 --auto --right-of HDMI1
-    elif [ -n "$HDMI1" -a -z "$VGA1" ]; then
-        echo "$prefix SETTING: HDMI1 (Primary)"
-        xrandr --output LVDS1 --off \
-               --output VGA1 --off \
-               --output HDMI1 --auto --primary
-    elif [ -z "$HDMI1" -a -n "$VGA1" ]; then
-        echo "$prefix SETTING: VGA1 (Primary)"
-        xrandr --output LVDS1 --off \
-               --output HDMI1 --off \
-               --output VGA1 --auto --primary
-    else
-        echo "$prefix No external monitors are plugged in"
-        xrandr --output HDMI1 --off \
-               --output VGA1 --off \
-               --output LVDS1 --auto --primary
-    fi
+config_closed_lid() {
+  if [ "$lidstatus" == "closed" ]; then
+    echo "$prefix Laptop lid is closed"
+  elif [ -n "$LVDS1" -a -z "$lidtest" ]; then
+    echo "$prefix Laptop display will be ignored unless -l option is set"
+  fi
+
+  if [ -n "$HDMI1" -a -n "$VGA1" ]; then
+    echo "$prefix SETTING: HDMI1 (Primary) - VGA1 (Right)"
+    xrandr --output LVDS1 --off \
+            --output HDMI1 --auto --primary \
+            --output VGA1 --auto --right-of HDMI1
+  elif [ -n "$HDMI1" -a -z "$VGA1" ]; then
+    echo "$prefix SETTING: HDMI1 (Primary)"
+    xrandr --output LVDS1 --off \
+            --output VGA1 --off \
+            --output HDMI1 --auto --primary
+  elif [ -z "$HDMI1" -a -n "$VGA1" ]; then
+    echo "$prefix SETTING: VGA1 (Primary)"
+    xrandr --output LVDS1 --off \
+            --output HDMI1 --off \
+            --output VGA1 --auto --primary
+  else
+    echo "$prefix No external monitors are plugged in"
+    xrandr --output HDMI1 --off \
+            --output VGA1 --off \
+            --output LVDS1 --auto --primary
+  fi
 }
 
 ## Configure monitors for open lid
-config_open_lid ()
-{
-    echo "$prefix Laptop lid is open"
-    if [ -n "$HDMI1" -a -n "$VGA1" ]; then
-        echo "$prefix SETTING: LVDS1 (Left) - HDMI1 (Primary) - VGA1 (Right)"
-        xrandr --output LVDS1 --off \
-               --output HDMI1 --auto --primary \
-               --output VGA1 --auto --right-of HDMI1
-    elif [ -n "$HDMI1" -a -z "$VGA1" ]; then
-        echo "$prefix HDMI1 is plugged in, but not VGA1"
-        echo "$prefix SETTING: LVDS1 (Primary) - HDMI1 (Right)"
-        xrandr --output VGA1 --off \
-               --output LVDS1 --auto --primary \
-               --output HDMI1 --auto --right-of LVDS1 --noprimary
-    elif [ -z "$HDMI1" -a -n "$VGA1" ]; then
-        echo "$prefix SETTING: LVDS1 (Primary) - VGA1 (Right)"
+config_open_lid() {
+  echo "$prefix Laptop lid is open"
+
+  xrandr --auto &&
+
+    if [ -n "$HDMI1" -a -n "$DP1" ]; then
+    echo "$prefix SETTING: DP1 (Left) - eDP1 (Middlle) - HDMI1 (Right - Primary)"
+    xrandr --output DP1 --auto --left-of eDP1 \
+           --output eDP1 --auto --left-of HDMI1 \
+           --output HDMI1 --auto --primary
+
+    elif [ -n "$HDMI1" -a -z "$DP1" ]; then
+        echo "$prefix HDMI1 is plugged in, but not DP1"
+        echo "$prefix SETTING: eDP1 (Left) - HDMI1 (Right - Primary)"
+        xrandr --output DP1 --off \
+               --output eDP1 --auto --left-of HDMI1 --noprimary \
+               --output HDMI1 --auto --primary
+
+    elif [ -z "$HDMI1" -a -n "$DP1" ]; then
+        echo "$prefix DP1 is plugged in, but not HDM1"
+        echo "$prefix SETTING: DP1 (Left) - eDP1 (Right - Primary)"
         xrandr --output HDMI1 --off \
-               --output LVDS1 --auto --primary \
-               --output VGA1 --auto --right-of LVDS1 --noprimary
+               --output DP1 --auto --left-of eDP1 --noprimary \
+               --output eDP1 --auto --primary
+
     else
         echo "$prefix No external monitors are plugged in"
         xrandr --output HDMI1 --off \
-               --output VGA1 --off \
-               --output LVDS1 --auto --primary
+               --output DP1 --off \
+               --output eDP1 --auto --primary
     fi
 }
 
-configure_displays ()
-{
+configure_displays () {
+  handle_err
 
-    handle_err
+  declare_outputs
 
-    declare_outputs
+  if [ -z "$lidstatus" -o "$lidstatus" == "closed" ]; then
+      config_closed_lid
+  elif [ "$lidstatus" == "open" ]; then
+      config_open_lid
+  fi
 
-    if [ -z "$lidstatus" -o "$lidstatus" == "closed" ]; then
-        config_closed_lid
-    elif [ "$lidstatus" == "open" ]; then
-        config_open_lid
-    fi
-
-    # Run .fehbg script if -f argument is given.
-    if [ "$fehbg" == "true" ]; then
-        if [ -x $HOME/.fehbg ]; then
-            echo "$prefix Setting background using .fehbg."
-            $($HOME/.fehbg 2>/dev/null)
-        else
-            echo ".$prefix Failed to execute ~/.fehbg script. Use 'feh --bg-xxx' to generate one."
-        fi
-    fi
+  # Run .fehbg script if -f argument is given.
+  if [ "$fehbg" == "true" ]; then
+      if [ -x $HOME/.fehbg ]; then
+          echo "$prefix Setting background using .fehbg."
+          $($HOME/.fehbg 2>/dev/null)
+      else
+          echo ".$prefix Failed to execute ~/.fehbg script. Use 'feh --bg-xxx' to generate one."
+      fi
+  fi
 
 	# FIXME: Prevent segfault occurring from simultanious signals. -- Issue #5 --
 	sleep 2
-
 }
 
 #-----------#
@@ -193,7 +205,6 @@ configure_displays ()
 trap "echo 'Received interrupt. Exiting...' ; exit" SIGHUP SIGINT SIGQUIT
 
 # Log output.
-#prefix='[ display-visor: ]:'
 exec 1> >(logger -s -t "display-visor") 2>&1
 
 # Handle arguments.
@@ -208,6 +219,6 @@ trap "echo 'Received signal. Reconfiguring displays.' ; configure_displays" RTMI
 # Wait for signals
 while :
 do
-    sleep 60 &
-    wait 
+  sleep 60 &
+  wait 
 done
